# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True, db_index=True, verbose_name='\u0412\u0440\u0435\u043c\u044f')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='\u0421\u0443\u043c\u043c\u0430')),
                ('result_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442')),
            ],
            options={
                'verbose_name': '\u0421\u0434\u0435\u043b\u043a\u0430',
                'verbose_name_plural': '\u0421\u0434\u0435\u043b\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u0418\u043c\u044f')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='\u0411\u0430\u043b\u0430\u043d\u0441')),
            ],
            options={
                'verbose_name': '\u0422\u0440\u0435\u0439\u0434\u0435\u0440',
                'verbose_name_plural': '\u0422\u0440\u0435\u0439\u0434\u0435\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True, verbose_name='\u0412\u0440\u0435\u043c\u044f')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='\u0421\u0443\u043c\u043c\u0430')),
                ('type', models.SmallIntegerField(choices=[(1, '\u0414\u0435\u043f\u043e\u0437\u0438\u0442'), (2, '\u0412\u044b\u0432\u043e\u0434')], verbose_name='\u0422\u0438\u043f \u0442\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u0438')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='trading.Trader')),
            ],
            options={
                'verbose_name': '\u0422\u0440\u0430\u043d\u0437\u0430\u0430\u043a\u0446\u0438\u044f',
                'verbose_name_plural': '\u0422\u0440\u0430\u043d\u0437\u0430\u0430\u043a\u0446\u0438\u0438',
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='trading.Trader'),
        ),
        migrations.AlterIndexTogether(
            name='transaction',
            index_together=set([('type', 'trader', 'amount')]),
        ),
    ]
