# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_created=True, verbose_name='\u0412\u0440\u0435\u043c\u044f')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='\u0421\u0443\u043c\u043c\u0430')),
                ('result_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430',
            },
        ),
        migrations.AddField(
            model_name='trader',
            name='total_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='\u041e\u0431\u0449\u0438\u0439 \u0434\u0435\u043f\u043e\u0437\u0438\u0442'),
        ),
        migrations.AddField(
            model_name='trader',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='\u041e\u0431\u0449\u0430\u044f \u043f\u0440\u0438\u0431\u044b\u043b\u044c'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='\u0411\u0430\u043b\u0430\u043d\u0441'),
        ),
        migrations.AddField(
            model_name='dealstat',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealstats', to='trading.Trader'),
        ),
        migrations.AlterUniqueTogether(
            name='dealstat',
            unique_together=set([('time', 'trader')]),
        ),
    ]
